version: '3.8'

services:
  django_backend:
    container_name: 'app'
    build: ./online_store
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./online_store/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=online_store

volumes:
  postgres_data:
