# Generated by Django 4.1.1 on 2022-09-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_bay',
            field=models.IntegerField(default=0, verbose_name='count_purchases'),
        ),
        migrations.AddField(
            model_name='product',
            name='limited_edition',
            field=models.BooleanField(default=False, verbose_name='limited edition'),
        ),
    ]
