# Generated by Django 4.1.1 on 2022-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_count_bay_product_limited_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='select_group',
            field=models.BooleanField(default=False, verbose_name='select group'),
        ),
    ]
