# Generated by Django 4.1.1 on 2022-09-30 15:25

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_catalog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.user_directory_path, verbose_name='photo'),
        ),
    ]
