# Generated by Django 4.1.1 on 2022-09-30 15:43

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_catalog_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='photo',
        ),
        migrations.CreateModel(
            name='PhotoCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=products.models.user_directory_path, verbose_name='photo')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.catalog', verbose_name='catalog')),
            ],
            options={
                'verbose_name': 'photo catalog',
                'verbose_name_plural': 'photo catalogs',
            },
        ),
    ]
