# Generated by Django 4.1.1 on 2022-10-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'purchased'), ('e', 'errors'), ('w', 'waiting for payment')], default='w', max_length=1, verbose_name='status pay'),
        ),
    ]
