# Generated by Django 4.1.1 on 2022-10-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(choices=[('f', 'free'), ('p', 'paid')], default='p', verbose_name='type delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_pay',
            field=models.CharField(choices=[('o', 'online cart'), ('s', 'payment from someone else account')], default='c', max_length=1, verbose_name=' type pay'),
        ),
    ]
