# Generated by Django 4.1.1 on 2022-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(choices=[('f', 'free'), ('p', 'paid')], verbose_name='type delivery'),
        ),
    ]
