# Generated by Django 4.1.1 on 2022-10-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('f', 'free'), ('p', 'paid')], default='p', max_length=1, verbose_name='type delivery'),
        ),
    ]
