# Generated by Django 4.1.1 on 2022-10-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_pay',
            field=models.CharField(choices=[('o', 'online cart'), ('s', 'payment from someone else account')], default='c', max_length=1, verbose_name='type pay'),
        ),
    ]
