# Generated by Django 4.1.1 on 2022-11-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options'),
        ('orders', '0007_alter_order_type_pay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('o', 'ordinary'), ('e', 'express')], default='p', max_length=1, verbose_name='type delivery'),
        ),
    ]
