# Generated by Django 4.1.1 on 2022-11-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_pay',
            field=models.CharField(choices=[('o', 'online cart'), ('s', 'payment from someone else account')], default='o', max_length=1, verbose_name='type pay'),
        ),
    ]
