# Generated by Django 4.1.1 on 2022-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_type_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='errors',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='error'),
        ),
    ]
